type ProductSeedData = {
    name: string;
    description: string;
    image: string; //eg: `/uploads/image.png`
    price: number;
    categoryId: string;
}

/* 

use the below ids for categoryId
categoryIds: [
  "1Mmg40056eL63JqcDNKaW",
  "5Ac3687ZVYkQqwbMH6A-x",
  "692d826f033a36199bd4df6c",
  "9HGZQ8FZ_DmcwmKZHUsbP",
  "CxcNjt0iaYg1GrJVaMq_b",
  "J4MS3o-RNl29FgtUtXp5K",
  "LzRuJez1Xc3SrsUKCVrn-",
  "Rg5NNnsnZcf2bQDn48Mpk",
  "SAUFUBa_mZIDvvDo5IFJT",
  "TixRyXGLCMzpUTvYz-2Nj",
  "ZJjZ-BNv1eLM_SqGkFkEI",
  "cCAc70Hf0IGx8gsbyRdDM",
  "mhzseJyrfIH_EPQc0hKUh",
  "tYJhwSK6k2_Ns0CE60OMg"
]

*/

export const electronicProductSeeds: ProductSeedData[] = [
    {
        name: 'NovaCore Pro 15',
        description:
            '15-inch OLED laptop with a 12th-gen CPU, 16 GB RAM, and a lightweight chassis for creators on the go.',
        image: '/uploads/novacore-pro-15.jpg',
        price: 1499,
        categoryId: '1Mmg40056eL63JqcDNKaW',
    },
    {
        name: 'SignalWave 5G Fold',
        description: 'Dual-screen 5G smartphone with adaptive refresh and an integrated stylus for note taking.',
        image: '/uploads/signalwave-5g-fold.jpg',
        price: 1199,
        categoryId: '5Ac3687ZVYkQqwbMH6A-x',
    },
    {
        name: 'ArcticBreeze Wireless Earbuds',
        description: 'Active noise canceling, multi-device pairing, and 30-hour battery life in a compact case.',
        image: '/uploads/arcticbreeze-earbuds.png',
        price: 199,
        categoryId: '692d826f033a36199bd4df6c',
    },
    {
        name: 'PulseDrive Pro SSD 2TB',
        description: 'High-speed NVMe storage with thermal shielding and a 5-year endurance warranty.',
        image: '/uploads/pulsedrive-ssd.png',
        price: 259,
        categoryId: '9HGZQ8FZ_DmcwmKZHUsbP',
    },
    {
        name: 'Solaris Edge 34',
        description: 'Curved 34-inch ultrawide monitor with quantum dot color and 144 Hz refresh.',
        image: '/uploads/solaris-edge-34.jpg',
        price: 599,
        categoryId: 'CxcNjt0iaYg1GrJVaMq_b',
    },
    {
        name: 'VectorOne Titan',
        description: 'Titanium smart watch with onboard LTE, health tracking, and two-day battery life.',
        image: '/uploads/vectorone-titan.jpg',
        price: 349,
        categoryId: 'J4MS3o-RNl29FgtUtXp5K',
    },
    {
        name: 'HaloBeam Home Projector',
        description: 'Compact laser projector with Android TV, 4K upscaling, and 2000-lumen brightness.',
        image: '/uploads/halobeam-projector.jpg',
        price: 899,
        categoryId: 'LzRuJez1Xc3SrsUKCVrn-',
    },
    {
        name: 'SkyLink Mesh Router',
        description: 'Tri-band mesh kit with WPA3 security and automatic channel optimization for dense homes.',
        image: '/uploads/skylink-mesh-router.jpg',
        price: 299,
        categoryId: 'Rg5NNnsnZcf2bQDn48Mpk',
    },
    {
        name: 'QuantumGrip Mechanical Keyboard',
        description: 'Hot-swappable switches, programmable macros, and per-key RGB in a low-profile frame.',
        image: '/uploads/quantumgrip-keyboard.jpg',
        price: 189,
        categoryId: 'SAUFUBa_mZIDvvDo5IFJT',
    },
    {
        name: 'Firefly Smart Lighting Kit',
        description: 'Wi-Fi bulbs and strips with adaptive scenes, voice control, and energy monitoring.',
        image: '/uploads/firefly-lighting.jpg',
        price: 149,
        categoryId: 'TixRyXGLCMzpUTvYz-2Nj',
    },
    {
        name: 'AeroPulse Compact Drone',
        description: 'Foldable drone with 4K camera, automated flight paths, and collision sensing.',
        image: '/uploads/aeropulse-drone.jpg',
        price: 679,
        categoryId: 'ZJjZ-BNv1eLM_SqGkFkEI',
    },
    {
        name: 'EchoWave Streaming Bar',
        description: 'Soundbar with Dolby Atmos simulation, built-in voice assistant, and HDMI eARC.',
        image: '/uploads/echowave-soundbar.jpeg',
        price: 349,
        categoryId: 'cCAc70Hf0IGx8gsbyRdDM',
    },
    {
        name: 'LumenStrand VR Kit',
        description: 'Wireless VR headset with inside-out tracking, mixed reality passthrough, and 120 Hz refresh.',
        image: '/uploads/lumenstrand-vr.jpg',
        price: 599,
        categoryId: 'mhzseJyrfIH_EPQc0hKUh',
    },
    {
        name: 'Nimbus Smart Thermostat',
        description: 'AI-powered climate control with remote sensors and energy reports.',
        image: '/uploads/nimbus-thermostat.jpg',
        price: 229,
        categoryId: 'tYJhwSK6k2_Ns0CE60OMg',
    },
    {
        name: 'VectorPixel Studio Camera',
        description: 'Mirrorless hybrid camera with dual card slots, 8K video, and speedy autofocus.',
        image: '/uploads/vectorpixel-camera.jpg',
        price: 1499,
        categoryId: '1Mmg40056eL63JqcDNKaW',
    },
    {
        name: 'VoltBoost HyperCharger',
        description: '65W GaN charger with dual USB-C ports and GaN cooling for travel-ready power.',
        image: '/uploads/voltboost-charger.jpg',
        price: 49,
        categoryId: '5Ac3687ZVYkQqwbMH6A-x',
    },
    {
        name: 'PrismTrack Fitness Band',
        description: 'Ultra-thin tracker with blood oxygen monitoring, guided workouts, and swimproof housing.',
        image: '/uploads/prismtrack-band.jpg',
        price: 129,
        categoryId: '692d826f033a36199bd4df6c',
    },
    {
        name: 'Titanium Soundbar Max',
        description: 'Modular soundbar with detachable subwoofer, HDMI 2.1, and room equalization.',
        image: '/uploads/titanium-soundbar.jpeg',
        price: 549,
        categoryId: '9HGZQ8FZ_DmcwmKZHUsbP',
    },
    {
        name: 'Aurora Studio Microphone',
        description: 'USB-C condenser mic with onboard DSP presets and a shock-mounted grille.',
        image: '/uploads/aurora-microphone.jpg',
        price: 279,
        categoryId: 'CxcNjt0iaYg1GrJVaMq_b',
    },
    {
        name: 'OrbitLink Smart Display',
        description: '10-inch smart display with adaptive brightness, built-in hub for routines, and stereo speakers.',
        image: '/uploads/orbitlink-display.jpg',
        price: 249,
        categoryId: 'J4MS3o-RNl29FgtUtXp5K',
    },
    {
        name: 'LumaFlex Portable Monitor',
        description: 'USB-C portable monitor with HDR support, anti-glare coating, and magnet folio stand.',
        image: '/uploads/lumaflex-monitor.jpg',
        price: 359,
        categoryId: 'LzRuJez1Xc3SrsUKCVrn-',
    },
    {
        name: 'NexaMotion Security Drone',
        description: 'Tether-ready security drone with HD thermal imaging and automatic patrol routes.',
        image: '/uploads/nexamotion-drone.jpg',
        price: 899,
        categoryId: 'Rg5NNnsnZcf2bQDn48Mpk',
    },
    {
        name: 'Zenith Graphene Power Bank',
        description: 'Graphene cell pack with 25,000 mAh, three simultaneous outputs, and passthrough charging.',
        image: '/uploads/zenith-powerbank.jpg',
        price: 119,
        categoryId: 'SAUFUBa_mZIDvvDo5IFJT',
    },
    {
        name: 'RippleFlow Smart Speaker',
        description: '360-degree smart speaker with adaptive EQ, ambient lighting, and multiroom support.',
        image: '/uploads/rippleflow-speaker.jpg',
        price: 199,
        categoryId: 'TixRyXGLCMzpUTvYz-2Nj',
    },
    {
        name: 'Polaris Racing Simulator Wheel',
        description: 'Direct-drive racing wheel with 900-degree rotation and programmable feedback profiles.',
        image: '/uploads/polaris-wheel.jpg',
        price: 429,
        categoryId: 'ZJjZ-BNv1eLM_SqGkFkEI',
    },
    {
        name: 'EchoSight Night Vision Camera',
        description: 'Outdoor security camera with 4K HDR, infrared, and AI vehicle/person alerts.',
        image: '/uploads/echosight-camera.jpeg',
        price: 329,
        categoryId: 'cCAc70Hf0IGx8gsbyRdDM',
    },
    {
        name: 'GlideStream Wi-Fi 6E Bridge',
        description: 'Low-profile bridge for wired devices with 7 Gbps throughput and redundant uplinks.',
        image: '/uploads/glidestream-bridge.jpg',
        price: 179,
        categoryId: 'mhzseJyrfIH_EPQc0hKUh',
    },
    {
        name: 'MagnaCore Desktop Workstation',
        description: 'Workstation tower with ECC memory, liquid cooling, and workstation GPU for CAD.',
        image: '/uploads/magnacore-workstation.jpg',
        price: 2399,
        categoryId: 'tYJhwSK6k2_Ns0CE60OMg',
    },
    {
        name: 'Nebula Touch Mixer',
        description: 'Smart audio mixer with touch faders, USB-C, Ethernet control, and embedded DSP.',
        image: '/uploads/nebula-mixer.jpg',
        price: 649,
        categoryId: '1Mmg40056eL63JqcDNKaW',
    },
    {
        name: 'CircuitFlow Debug Kit',
        description: 'Portable electronics bench kit with high-resolution scope and programmable logic analyzer.',
        image: '/uploads/circuitflow-kit.png',
        price: 159,
        categoryId: '5Ac3687ZVYkQqwbMH6A-x',
    },
    {
        name: 'OpticPulse Glass Camera',
        description: 'Smart glasses with dual cameras, voice control, and bone-conduction audio.',
        image: '/uploads/opticpulse-glasses.jpg',
        price: 799,
        categoryId: '692d826f033a36199bd4df6c',
    },
    {
        name: 'Horizon Smart Photo Frame',
        description: 'Minimal smart frame with cloud sync, auto-rotation, and gesture navigation.',
        image: '/uploads/horizon-frame.jpg',
        price: 189,
        categoryId: '9HGZQ8FZ_DmcwmKZHUsbP',
    },
    {
        name: 'StratoLink Satellite Modem',
        description: 'Portable satellite modem with mesh failover, 10-hour battery, and IPv6 support.',
        image: '/uploads/stratolink-modem.png',
        price: 469,
        categoryId: 'CxcNjt0iaYg1GrJVaMq_b',
    },
    {
        name: 'FusionDrive NAS 4-Bay',
        description: 'Enterprise-grade NAS with hardware encryption, 10 GbE, and dual controllers.',
        image: '/uploads/fusiondrive-nas.jpg',
        price: 1249,
        categoryId: 'J4MS3o-RNl29FgtUtXp5K',
    },
    {
        name: 'PulseSense Air Monitor',
        description: 'IoT air quality monitor with particulate sensors, VOC detection, and mobile alerts.',
        image: '/uploads/pulsesense-monitor.jpg',
        price: 199,
        categoryId: 'LzRuJez1Xc3SrsUKCVrn-',
    },
    {
        name: 'Radiant Flow RGB Panel',
        description: 'Modular LED panel that syncs to music, supports presets, and daisy-chains via RGBlink.',
        image: '/uploads/radiant-panel.jpeg',
        price: 219,
        categoryId: 'Rg5NNnsnZcf2bQDn48Mpk',
    },
    {
        name: 'VividCore Studio Light',
        description: 'Tunable bicolor panel with wireless control, diffusion filters, and battery mount.',
        image: '/uploads/vividcore-light.jpg',
        price: 279,
        categoryId: 'SAUFUBa_mZIDvvDo5IFJT',
    },
    {
        name: 'AtlasMap Portable GPS',
        description: 'Handheld GPS unit with offline maps, rugged housing, and satellite messenger.',
        image: '/uploads/atlasmap-gps.png',
        price: 189,
        categoryId: 'TixRyXGLCMzpUTvYz-2Nj',
    },
    {
        name: 'AdeptLink USB-C Dock',
        description: 'Thunderbolt dock with 4K display ports, 85W charging, and dual Ethernet.',
        image: '/uploads/adeptlink-dock.jpeg',
        price: 139,
        categoryId: 'ZJjZ-BNv1eLM_SqGkFkEI',
    },
    {
        name: 'NeuroLite Wellness Lamp',
        description: 'Circadian lamp with sunrise/sunset presets, Bluetooth control, and low blue light spectrum.',
        image: '/uploads/neurolite-lamp.png',
        price: 229,
        categoryId: 'cCAc70Hf0IGx8gsbyRdDM',
    },
];
